version: 2
updates:
  #Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "DependabotPR"
      include: "scope"
    labels:
      - npm
      - dependencies
    target-branch: "master"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2

  # Maintain dependencies for Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "rails"
    versioning-strategy: lockfile-only
    commit-message:
      prefix: "DependabotPR"
      include: "scope"
    labels:
      - bundler
      - dependencies
    target-branch: "master"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
